set noanti
"set nomacatsui
set guioptions=aegiMt
set gfn=Bitstream\ Vera\ Sans\ Mono\ 8
"colorscheme vividchalk
colorscheme paintbox

"highlight StatusLine    guifg=Black   guibg=#aabbee gui=bold ctermfg=Black ctermbg=White  cterm=bold
"highlight StatusLineNC  guifg=#444444 guibg=#888888 gui=none ctermfg=Black ctermbg=Grey   cterm=none

highlight Cursor        guifg=Black guibg=Magenta ctermfg=Black ctermbg=White
	":highlight Folded guibg=grey guifg=blue
	":highlight FoldColumn guibg=darkgrey guifg=white

"highlight VertSplit		guifg=Black guibg=White

"highlight Folded			guibg=#333333

"set background=light
set cursorline

