#!/usr/bin/zsh

if [[ -n "${TMUX}" ]] tmux rename-window "Django"
print -Pn "\e]0;Django Launcher\a"

local manage menu answer

typeset -A menu
menu=(
	d	dbshell
	r	runserver
	s	shell
)

print "\t Launch:"
for key in ${(k)menu}; do
	print "\t${key}   ${menu[$key]}"
done
print "\t?"

read -q answer
print

case "${answer}" in
	'r' )
		
		if [[ -n "${TMUX}" ]] tmux set-window-option monitor-activity on
		;;
esac

if [[ -n "${TMUX}" ]] tmux rename-window "${menu[$answer]}"
print -Pn "\e]0;Django ${menu[$answer]}\a"

manage=$(find -name manage.py -type f)

"${manage}" "${menu[$answer]}"

