#!/bin/bash

echo "Searching for inve-script..."

inve=$(find * .virtualenv -wholename '*/bin/inve' 2> /dev/null)

if [[ -z "${inve}" ]]; then
	echo "Couldn't find an inve-script"
	exit -1
fi

alternative_count=$(echo "${inve}" | wc -l | tr -d "[:space:]")
if [[ $alternative_count -gt 1 ]]; then
	if fzf --help &> /dev/null; then
		inve=$(fzf --height=$(( 2 + ${alternative_count} )) --header="Choose virtual environment" <<< "${inve}") || exit -1
	else
		echo "Found several scripts:"
		echo "${inve}" | sed "s/^/\t/"
		exit -2
	fi
fi

echo "Found inve at ${inve}"
exec "${inve}" $@
